### ISSUE TITLE
v2 TODO

### ISSUE THREAD

**Issue by timmo001** [timmo001/home-panel#333]
# TODO

- [x] Custom icons (Pull current button)
- [x] Check if entities exist and error card if missing.
- [x] Any unavailable entities should be greyed and disabled
- [x] Where possible, make larger cards show dialog content / No long clicks for lights etc.
- [x] :building_construction: Add edit and delete pages functionality
- [x] Pages
- [x] :bug: Fix group delete position
- [x] Group editing
- [x] Auto hide toolbar (option)
- [x] Fix round
- [x] Themes
- [x] :bug: Fix select mapping issue when light state changes (unavailable to on)
- [x] Scrolling works past bounds
- [x] :key: Cleanup and test login screen
- [x] :books: Updated docs
- [x] :art: Updated screenshots

## Compatible Entities

- [x] air_quality
- [x] alarm_control_panel
- [x] binary_sensor
- [x] camera
- [x] climate
- [x] cover
- [x] fan
- [x] geo_location
- [x] light
- [x] lock
- [x] media_player
- [x] remote
- [x] scene
- [x] script
- [x] sensor
- [x] switch
- [x] sun
- [x] weather
